data:
  usaspending_url: "https://api.usaspending.gov/api/v2"
  sample_size: 100000
  random_seed: 42
  test_size: 0.2
  val_size: 0.1

synthetic:
  n_suppliers: 500
  n_components: 1000
  n_contracts: 5000
  n_countries: 30
  disruption_rate: 0.12
  cost_anomaly_rate: 0.08
  random_seed: 42

graph:
  edge_threshold: 0.3
  max_neighbors: 15
  node_types:
    - supplier
    - component
    - country
    - contract
    - route

gnn:
  model_type: "GraphSAGE"
  hidden_channels: 128
  num_layers: 3
  dropout: 0.3
  learning_rate: 0.001
  weight_decay: 0.0005
  epochs: 200
  patience: 30
  batch_size: 64

agents:
  model: "claude-sonnet-4-20250514"
  max_tokens: 1000
  temperature: 0.1
  cache_responses: true
  mock_mode: false

api:
  host: "0.0.0.0"
  port: 8000

dashboard:
  port: 8050
  debug: false

training:
  mlflow_experiment: "procure-iq"
  mlflow_tracking_uri: "mlflow_tracking/"
  device: "cpu"
